#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/notification-daemon.desktop 3.17.2-2~ notification-daemon -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/notification-daemon-autostart.desktop 3.20.0-1~ notification-daemon -- "$@"
# End automatically added section
